export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const CHANGE_UNITS = 'CHANGE_UNITS';
export const SELECT_DAY_FORECAST = 'SELECT_DAY_FORECAST';
export const SET_ERROR = 'SET_ERROR';
